//internal imports
import React from "react";
import "@styles/custom.css";
import Providers from "./provider";
import {
  getStoreSetting,
  getGlobalSetting,
  getStoreCustomizationSetting,
} from "@services/SettingServices";

import { SettingProvider } from "@context/SettingContext";

// Force dynamic rendering to avoid long static generation during builds
export const dynamic = "force-dynamic";
export const revalidate = 0;

export const metadata = {
  title: "Kachabazar - Next Store e-commerce Template",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // Fetch settings with error handling - use defaults if API fails
  const globalResult = await getGlobalSetting();
  const storeResult = await getStoreSetting();
  const customizationResult = await getStoreCustomizationSetting();

  const globalSetting = globalResult.globalSetting || {};
  const storeSetting = storeResult.storeSetting || {};
  const storeCustomizationSetting = customizationResult.storeCustomizationSetting || {};

  return (
    <html lang="en" className="" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className="bg-white antialiased dark:bg-zinc-900"
      >
        <div>
          <SettingProvider
            initialGlobalSetting={globalSetting}
            initialStoreSetting={storeSetting}
            initialCustomizationSetting={storeCustomizationSetting}
          >
            <Providers storeSetting={storeSetting}>
              {children}
            </Providers>
          </SettingProvider>
        </div>
      </body>
    </html>
  );
}
